### ISSUE TITLE
Timer not working

### ISSUE THREAD

**Issue by hemanzur** [greiman/FreeRTOS-Arduino#2]
Thanks for this port of FreeRTOs to Arduino.
I've been working with the examples and so far it works great.

I've been having some trouble working with timers.
I'm trying to upload this code to a MEGA2560 using arduino IDE 1.6.5:

``` c++
#include <FreeRTOS_AVR.h>
#include <basic_io_avr.h>
#include "utility/timers.h"

TimerHandle_t timer1;

void setup() {
  // put your setup code here, to run once:
  Serial.begin(9600);
  int x=1;
  //xTimerCreate();
  timer1 = xTimerCreate("timer1", 500, pdFALSE, (void*)x, timer1_callback);
  Serial.print("Before execution: ");
  Serial.println(millis());

  xTimerStart(timer1, 0);
  vTaskStartScheduler();
  for( ;; );
}

void loop() {}

void timer1_callback( TimerHandle_t pxTimer){
  Serial.println("Ready !");
}
```

But it doesn't compile:

```
timer_test.cpp.o: In function `setup':
/opt/arduino/timer_test.ino:12: undefined reference to `xTimerCreate'
/opt/arduino/timer_test.ino:16: undefined reference to `xTimerGenericCommand'
collect2: error: ld returned 1 exit status
Error compiling.
```

Seems to be a problem of the compiler not recognizing those functions.

Any ideas,
Thanks

**Comment by greiman** [comment]
I did not enable software timers since a number of resources are required.

You can enable software timers but a number of configuration parameters are required.  I have not used software timers on FreeRTOS so I can't help you.

See:

http://www.freertos.org/FreeRTOS-Software-Timer-API-Functions.html

You must define values for at least these symbols for your application:

configUSE_TIMERS

INCLUDE_xTimerGetTimerDaemonTaskHandle

configTIMER_TASK_PRIORITY

configTIMER_QUEUE_LENGTH

configTIMER_TASK_STACK_DEPTH
